#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

# Clear and copy fields
cp -r 0.og 0

runApplication setFields 

# Get application name
application=`getApplication`

runApplication `getApplication`

#-----------------------------------------------------------------------------
